//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibationAvalonia.Properties
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;

		internal Resources()
		{
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					var temp = new global::System.Resources.ResourceManager("LibationAvalonia.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get => resourceCulture;
			set => resourceCulture = value;
		}

		public static string RouteOverviewLabel => ResourceManager.GetString("RouteOverviewLabel", resourceCulture);
		public static string RouteOverviewDescription => ResourceManager.GetString("RouteOverviewDescription", resourceCulture);
		public static string RouteLibraryLabel => ResourceManager.GetString("RouteLibraryLabel", resourceCulture);
		public static string RouteLibraryDescription => ResourceManager.GetString("RouteLibraryDescription", resourceCulture);
		public static string RouteDownloadsLabel => ResourceManager.GetString("RouteDownloadsLabel", resourceCulture);
		public static string RouteDownloadsDescription => ResourceManager.GetString("RouteDownloadsDescription", resourceCulture);
		public static string RouteProcessingLabel => ResourceManager.GetString("RouteProcessingLabel", resourceCulture);
		public static string RouteProcessingDescription => ResourceManager.GetString("RouteProcessingDescription", resourceCulture);
		public static string RouteHistoryLabel => ResourceManager.GetString("RouteHistoryLabel", resourceCulture);
		public static string RouteHistoryDescription => ResourceManager.GetString("RouteHistoryDescription", resourceCulture);
		public static string RouteAccountsLabel => ResourceManager.GetString("RouteAccountsLabel", resourceCulture);
		public static string RouteAccountsDescription => ResourceManager.GetString("RouteAccountsDescription", resourceCulture);
		public static string RouteSettingsLabel => ResourceManager.GetString("RouteSettingsLabel", resourceCulture);
		public static string RouteSettingsDescription => ResourceManager.GetString("RouteSettingsDescription", resourceCulture);
		public static string RouteToolsLabel => ResourceManager.GetString("RouteToolsLabel", resourceCulture);
		public static string RouteToolsDescription => ResourceManager.GetString("RouteToolsDescription", resourceCulture);
		public static string RouteTrashLabel => ResourceManager.GetString("RouteTrashLabel", resourceCulture);
		public static string RouteTrashDescription => ResourceManager.GetString("RouteTrashDescription", resourceCulture);
		public static string RouteAboutLabel => ResourceManager.GetString("RouteAboutLabel", resourceCulture);
		public static string RouteAboutDescription => ResourceManager.GetString("RouteAboutDescription", resourceCulture);
		public static string ShellCloseNavigationOverlayAutomationName => ResourceManager.GetString("ShellCloseNavigationOverlayAutomationName", resourceCulture);
		public static string ShellAboutPageTitle => ResourceManager.GetString("ShellAboutPageTitle", resourceCulture);
		public static string ShellAboutPageDescription => ResourceManager.GetString("ShellAboutPageDescription", resourceCulture);
		public static string ShellNavigationCommandLabel => ResourceManager.GetString("ShellNavigationCommandLabel", resourceCulture);
		public static string ShellOpenPrimaryNavigationAutomationName => ResourceManager.GetString("ShellOpenPrimaryNavigationAutomationName", resourceCulture);
		public static string ShellOpenAboutCommandLabel => ResourceManager.GetString("ShellOpenAboutCommandLabel", resourceCulture);
		public static string ShellOpenProcessingWorkspaceCommandLabel => ResourceManager.GetString("ShellOpenProcessingWorkspaceCommandLabel", resourceCulture);
		public static string ShellOpenProcessingSummaryAutomationName => ResourceManager.GetString("ShellOpenProcessingSummaryAutomationName", resourceCulture);
		public static string ShellOpenCurrentFlightAutomationName => ResourceManager.GetString("ShellOpenCurrentFlightAutomationName", resourceCulture);
		public static string ShellCurrentFlightCountFormat => ResourceManager.GetString("ShellCurrentFlightCountFormat", resourceCulture);
		public static string ShellCompactFlightCountFormat => ResourceManager.GetString("ShellCompactFlightCountFormat", resourceCulture);
		public static string ShellOpenCompactProcessingBarAutomationName => ResourceManager.GetString("ShellOpenCompactProcessingBarAutomationName", resourceCulture);
		public static string ShellCloseProcessingDrawerAutomationName => ResourceManager.GetString("ShellCloseProcessingDrawerAutomationName", resourceCulture);
		public static string ShellCloseCommandLabel => ResourceManager.GetString("ShellCloseCommandLabel", resourceCulture);
		public static string MenuImportHeader => ResourceManager.GetString("MenuImportHeader", resourceCulture);
		public static string MenuAutoScanLibraryHeader => ResourceManager.GetString("MenuAutoScanLibraryHeader", resourceCulture);
		public static string MenuAddAccountHeader => ResourceManager.GetString("MenuAddAccountHeader", resourceCulture);
		public static string MenuScanLibraryHeader => ResourceManager.GetString("MenuScanLibraryHeader", resourceCulture);
		public static string MenuScanAllAccountsHeader => ResourceManager.GetString("MenuScanAllAccountsHeader", resourceCulture);
		public static string MenuScanSomeAccountsHeader => ResourceManager.GetString("MenuScanSomeAccountsHeader", resourceCulture);
		public static string MenuRemoveLibraryBooksHeader => ResourceManager.GetString("MenuRemoveLibraryBooksHeader", resourceCulture);
		public static string MenuRemoveBooksAllAccountsHeader => ResourceManager.GetString("MenuRemoveBooksAllAccountsHeader", resourceCulture);
		public static string MenuRemoveBooksSomeAccountsHeader => ResourceManager.GetString("MenuRemoveBooksSomeAccountsHeader", resourceCulture);
		public static string MenuLocateAudiobooksHeader => ResourceManager.GetString("MenuLocateAudiobooksHeader", resourceCulture);
		public static string MenuLiberateHeader => ResourceManager.GetString("MenuLiberateHeader", resourceCulture);
		public static string MenuConvertAllM4BToMp3Header => ResourceManager.GetString("MenuConvertAllM4BToMp3Header", resourceCulture);
		public static string MenuExportHeader => ResourceManager.GetString("MenuExportHeader", resourceCulture);
		public static string MenuExportLibraryHeader => ResourceManager.GetString("MenuExportLibraryHeader", resourceCulture);
		public static string MenuQuickFiltersHeader => ResourceManager.GetString("MenuQuickFiltersHeader", resourceCulture);
		public static string MenuReplaceTagsHeader => ResourceManager.GetString("MenuReplaceTagsHeader", resourceCulture);
		public static string MenuSetBookDownloadedHeader => ResourceManager.GetString("MenuSetBookDownloadedHeader", resourceCulture);
		public static string MenuSetPdfDownloadedHeader => ResourceManager.GetString("MenuSetPdfDownloadedHeader", resourceCulture);
		public static string MenuSetDownloadedAutomaticallyHeader => ResourceManager.GetString("MenuSetDownloadedAutomaticallyHeader", resourceCulture);
		public static string MenuRemoveFromLibraryHeader => ResourceManager.GetString("MenuRemoveFromLibraryHeader", resourceCulture);
		public static string MenuSettingsHeader => ResourceManager.GetString("MenuSettingsHeader", resourceCulture);
		public static string MenuAccountsHeader => ResourceManager.GetString("MenuAccountsHeader", resourceCulture);
		public static string MenuOpenSettingsHeader => ResourceManager.GetString("MenuOpenSettingsHeader", resourceCulture);
		public static string MenuLaunchHangoverHeader => ResourceManager.GetString("MenuLaunchHangoverHeader", resourceCulture);
		public static string MenuScanForBetterQualityAudiobooksHeader => ResourceManager.GetString("MenuScanForBetterQualityAudiobooksHeader", resourceCulture);
		public static string MenuReviewContemporarySetupHeader => ResourceManager.GetString("MenuReviewContemporarySetupHeader", resourceCulture);
		public static string MenuAboutHeader => ResourceManager.GetString("MenuAboutHeader", resourceCulture);
		public static string ShellDoneReviewingCommandLabel => ResourceManager.GetString("ShellDoneReviewingCommandLabel", resourceCulture);
	}
}
