//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibationAvalonia.Properties
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;

		internal Resources()
		{
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					var temp = new global::System.Resources.ResourceManager("LibationAvalonia.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get => resourceCulture;
			set => resourceCulture = value;
		}

		public static string RouteOverviewLabel => ResourceManager.GetString("RouteOverviewLabel", resourceCulture);
		public static string RouteOverviewDescription => ResourceManager.GetString("RouteOverviewDescription", resourceCulture);
		public static string RouteLibraryLabel => ResourceManager.GetString("RouteLibraryLabel", resourceCulture);
		public static string RouteLibraryDescription => ResourceManager.GetString("RouteLibraryDescription", resourceCulture);
		public static string RouteDownloadsLabel => ResourceManager.GetString("RouteDownloadsLabel", resourceCulture);
		public static string RouteDownloadsDescription => ResourceManager.GetString("RouteDownloadsDescription", resourceCulture);
		public static string RouteProcessingLabel => ResourceManager.GetString("RouteProcessingLabel", resourceCulture);
		public static string RouteProcessingDescription => ResourceManager.GetString("RouteProcessingDescription", resourceCulture);
		public static string RouteHistoryLabel => ResourceManager.GetString("RouteHistoryLabel", resourceCulture);
		public static string RouteHistoryDescription => ResourceManager.GetString("RouteHistoryDescription", resourceCulture);
		public static string RouteAccountsLabel => ResourceManager.GetString("RouteAccountsLabel", resourceCulture);
		public static string RouteAccountsDescription => ResourceManager.GetString("RouteAccountsDescription", resourceCulture);
		public static string RouteSettingsLabel => ResourceManager.GetString("RouteSettingsLabel", resourceCulture);
		public static string RouteSettingsDescription => ResourceManager.GetString("RouteSettingsDescription", resourceCulture);
		public static string RouteToolsLabel => ResourceManager.GetString("RouteToolsLabel", resourceCulture);
		public static string RouteToolsDescription => ResourceManager.GetString("RouteToolsDescription", resourceCulture);
		public static string RouteTrashLabel => ResourceManager.GetString("RouteTrashLabel", resourceCulture);
		public static string RouteTrashDescription => ResourceManager.GetString("RouteTrashDescription", resourceCulture);
		public static string RouteAboutLabel => ResourceManager.GetString("RouteAboutLabel", resourceCulture);
		public static string RouteAboutDescription => ResourceManager.GetString("RouteAboutDescription", resourceCulture);
		public static string ShellCloseNavigationOverlayAutomationName => ResourceManager.GetString("ShellCloseNavigationOverlayAutomationName", resourceCulture);
		public static string ShellAboutPageTitle => ResourceManager.GetString("ShellAboutPageTitle", resourceCulture);
		public static string ShellAboutPageDescription => ResourceManager.GetString("ShellAboutPageDescription", resourceCulture);
		public static string ShellNavigationCommandLabel => ResourceManager.GetString("ShellNavigationCommandLabel", resourceCulture);
		public static string ShellOpenPrimaryNavigationAutomationName => ResourceManager.GetString("ShellOpenPrimaryNavigationAutomationName", resourceCulture);
		public static string ShellOpenAboutCommandLabel => ResourceManager.GetString("ShellOpenAboutCommandLabel", resourceCulture);
		public static string ShellOpenProcessingWorkspaceCommandLabel => ResourceManager.GetString("ShellOpenProcessingWorkspaceCommandLabel", resourceCulture);
		public static string ShellOpenProcessingSummaryAutomationName => ResourceManager.GetString("ShellOpenProcessingSummaryAutomationName", resourceCulture);
		public static string ShellOpenCurrentFlightAutomationName => ResourceManager.GetString("ShellOpenCurrentFlightAutomationName", resourceCulture);
		public static string ShellCurrentFlightCountFormat => ResourceManager.GetString("ShellCurrentFlightCountFormat", resourceCulture);
		public static string ShellCompactFlightCountFormat => ResourceManager.GetString("ShellCompactFlightCountFormat", resourceCulture);
		public static string ShellOpenCompactProcessingBarAutomationName => ResourceManager.GetString("ShellOpenCompactProcessingBarAutomationName", resourceCulture);
		public static string ShellCloseProcessingDrawerAutomationName => ResourceManager.GetString("ShellCloseProcessingDrawerAutomationName", resourceCulture);
		public static string ShellCloseCommandLabel => ResourceManager.GetString("ShellCloseCommandLabel", resourceCulture);
		public static string MenuImportHeader => ResourceManager.GetString("MenuImportHeader", resourceCulture);
		public static string MenuAutoScanLibraryHeader => ResourceManager.GetString("MenuAutoScanLibraryHeader", resourceCulture);
		public static string MenuAddAccountHeader => ResourceManager.GetString("MenuAddAccountHeader", resourceCulture);
		public static string MenuScanLibraryHeader => ResourceManager.GetString("MenuScanLibraryHeader", resourceCulture);
		public static string MenuScanAllAccountsHeader => ResourceManager.GetString("MenuScanAllAccountsHeader", resourceCulture);
		public static string MenuScanSomeAccountsHeader => ResourceManager.GetString("MenuScanSomeAccountsHeader", resourceCulture);
		public static string MenuRemoveLibraryBooksHeader => ResourceManager.GetString("MenuRemoveLibraryBooksHeader", resourceCulture);
		public static string MenuRemoveBooksAllAccountsHeader => ResourceManager.GetString("MenuRemoveBooksAllAccountsHeader", resourceCulture);
		public static string MenuRemoveBooksSomeAccountsHeader => ResourceManager.GetString("MenuRemoveBooksSomeAccountsHeader", resourceCulture);
		public static string MenuLocateAudiobooksHeader => ResourceManager.GetString("MenuLocateAudiobooksHeader", resourceCulture);
		public static string MenuLiberateHeader => ResourceManager.GetString("MenuLiberateHeader", resourceCulture);
		public static string MenuConvertAllM4BToMp3Header => ResourceManager.GetString("MenuConvertAllM4BToMp3Header", resourceCulture);
		public static string MenuExportHeader => ResourceManager.GetString("MenuExportHeader", resourceCulture);
		public static string MenuExportLibraryHeader => ResourceManager.GetString("MenuExportLibraryHeader", resourceCulture);
		public static string MenuQuickFiltersHeader => ResourceManager.GetString("MenuQuickFiltersHeader", resourceCulture);
		public static string MenuReplaceTagsHeader => ResourceManager.GetString("MenuReplaceTagsHeader", resourceCulture);
		public static string MenuSetBookDownloadedHeader => ResourceManager.GetString("MenuSetBookDownloadedHeader", resourceCulture);
		public static string MenuSetPdfDownloadedHeader => ResourceManager.GetString("MenuSetPdfDownloadedHeader", resourceCulture);
		public static string MenuSetDownloadedAutomaticallyHeader => ResourceManager.GetString("MenuSetDownloadedAutomaticallyHeader", resourceCulture);
		public static string MenuRemoveFromLibraryHeader => ResourceManager.GetString("MenuRemoveFromLibraryHeader", resourceCulture);
		public static string MenuSettingsHeader => ResourceManager.GetString("MenuSettingsHeader", resourceCulture);
		public static string MenuAccountsHeader => ResourceManager.GetString("MenuAccountsHeader", resourceCulture);
		public static string MenuOpenSettingsHeader => ResourceManager.GetString("MenuOpenSettingsHeader", resourceCulture);
		public static string MenuLaunchHangoverHeader => ResourceManager.GetString("MenuLaunchHangoverHeader", resourceCulture);
		public static string MenuScanForBetterQualityAudiobooksHeader => ResourceManager.GetString("MenuScanForBetterQualityAudiobooksHeader", resourceCulture);
		public static string MenuReviewContemporarySetupHeader => ResourceManager.GetString("MenuReviewContemporarySetupHeader", resourceCulture);
		public static string MenuAboutHeader => ResourceManager.GetString("MenuAboutHeader", resourceCulture);
		public static string ShellDoneReviewingCommandLabel => ResourceManager.GetString("ShellDoneReviewingCommandLabel", resourceCulture);
		public static string SupportedAudiobookFileTypes => ResourceManager.GetString("SupportedAudiobookFileTypes", resourceCulture);
		public static string DownloadsPipelineExplanation => ResourceManager.GetString("DownloadsPipelineExplanation", resourceCulture);
		public static string DownloadsFindAcquireExplanation => ResourceManager.GetString("DownloadsFindAcquireExplanation", resourceCulture);
		public static string DownloadsConvertExplanation => ResourceManager.GetString("DownloadsConvertExplanation", resourceCulture);
		public static string DownloadsEmptyScanningExplanation => ResourceManager.GetString("DownloadsEmptyScanningExplanation", resourceCulture);
		public static string DownloadsPendingExplanationFormat => ResourceManager.GetString("DownloadsPendingExplanationFormat", resourceCulture);
		public static string DownloadsPipelineActiveFormat => ResourceManager.GetString("DownloadsPipelineActiveFormat", resourceCulture);
		public static string DownloadsPipelineIdle => ResourceManager.GetString("DownloadsPipelineIdle", resourceCulture);
		public static string DownloadsRefreshUnchangedError => ResourceManager.GetString("DownloadsRefreshUnchangedError", resourceCulture);
		public static string ToolsSupportingText => ResourceManager.GetString("ToolsSupportingText", resourceCulture);
		public static string ToolsManualBookStatusDescription => ResourceManager.GetString("ToolsManualBookStatusDescription", resourceCulture);
		public static string ToolsManualPdfStatusDescription => ResourceManager.GetString("ToolsManualPdfStatusDescription", resourceCulture);
		public static string ToolsTrashDescription => ResourceManager.GetString("ToolsTrashDescription", resourceCulture);
		public static string ToolsFileDiscoveryDescription => ResourceManager.GetString("ToolsFileDiscoveryDescription", resourceCulture);
		public static string ToolsLocateDescription => ResourceManager.GetString("ToolsLocateDescription", resourceCulture);
		public static string ToolsQualityDescription => ResourceManager.GetString("ToolsQualityDescription", resourceCulture);
		public static string ToolsImportExportDescription => ResourceManager.GetString("ToolsImportExportDescription", resourceCulture);
		public static string ToolsEditFiltersDescription => ResourceManager.GetString("ToolsEditFiltersDescription", resourceCulture);
		public static string ToolsSaveFilterDescription => ResourceManager.GetString("ToolsSaveFilterDescription", resourceCulture);
		public static string ToolsFilterHelpDescription => ResourceManager.GetString("ToolsFilterHelpDescription", resourceCulture);
		public static string ToolsDiagnosticsDescription => ResourceManager.GetString("ToolsDiagnosticsDescription", resourceCulture);
		public static string ToolsAboutDescription => ResourceManager.GetString("ToolsAboutDescription", resourceCulture);
		public static string ToolsHangoverDescription => ResourceManager.GetString("ToolsHangoverDescription", resourceCulture);
		public static string SettingsSupportingText => ResourceManager.GetString("SettingsSupportingText", resourceCulture);
		public static string SettingsEmptyExplanation => ResourceManager.GetString("SettingsEmptyExplanation", resourceCulture);
		public static string SettingsUpdatesDescription => ResourceManager.GetString("SettingsUpdatesDescription", resourceCulture);
		public static string SettingsClassicColorSummary => ResourceManager.GetString("SettingsClassicColorSummary", resourceCulture);
		public static string OnboardingSupportingText => ResourceManager.GetString("OnboardingSupportingText", resourceCulture);
		public static string OnboardingWelcomeBody => ResourceManager.GetString("OnboardingWelcomeBody", resourceCulture);
		public static string OnboardingProfileChoiceWarning => ResourceManager.GetString("OnboardingProfileChoiceWarning", resourceCulture);
		public static string OnboardingHighContrastDescription => ResourceManager.GetString("OnboardingHighContrastDescription", resourceCulture);
		public static string OnboardingAccountPrivacy => ResourceManager.GetString("OnboardingAccountPrivacy", resourceCulture);
		public static string OnboardingLocationExplanation => ResourceManager.GetString("OnboardingLocationExplanation", resourceCulture);
		public static string OnboardingStorageReminder => ResourceManager.GetString("OnboardingStorageReminder", resourceCulture);
		public static string OnboardingScanExplanation => ResourceManager.GetString("OnboardingScanExplanation", resourceCulture);
		public static string OnboardingFlightExplanation => ResourceManager.GetString("OnboardingFlightExplanation", resourceCulture);
		public static string OnboardingStatusExplanation => ResourceManager.GetString("OnboardingStatusExplanation", resourceCulture);
		public static string OnboardingLibraryUnchangedTitle => ResourceManager.GetString("OnboardingLibraryUnchangedTitle", resourceCulture);
		public static string OnboardingLibraryUnchangedMessage => ResourceManager.GetString("OnboardingLibraryUnchangedMessage", resourceCulture);
		public static string HistoryEyebrow => ResourceManager.GetString("HistoryEyebrow", resourceCulture);
		public static string HistorySupportingText => ResourceManager.GetString("HistorySupportingText", resourceCulture);
		public static string HistoryScopeTitle => ResourceManager.GetString("HistoryScopeTitle", resourceCulture);
		public static string HistoryScopeMessage => ResourceManager.GetString("HistoryScopeMessage", resourceCulture);
		public static string AccountsScanIdle => ResourceManager.GetString("AccountsScanIdle", resourceCulture);
		public static string AccountsAuthorizationSummary => ResourceManager.GetString("AccountsAuthorizationSummary", resourceCulture);
		public static string AccountsReconcileExplanation => ResourceManager.GetString("AccountsReconcileExplanation", resourceCulture);
		public static string TrashPermanentWarning => ResourceManager.GetString("TrashPermanentWarning", resourceCulture);
		public static string TrashDeleteExplanation => ResourceManager.GetString("TrashDeleteExplanation", resourceCulture);
		public static string ProcessingNoFailuresExplanation => ResourceManager.GetString("ProcessingNoFailuresExplanation", resourceCulture);
		public static string ComponentGalleryQueueDetails => ResourceManager.GetString("ComponentGalleryQueueDetails", resourceCulture);
		public static string FlightQueueAccepted => ResourceManager.GetString("FlightQueueAccepted", resourceCulture);
		public static string FlightQueueRejected => ResourceManager.GetString("FlightQueueRejected", resourceCulture);
		public static string FlightDuplicateOutputFormat => ResourceManager.GetString("FlightDuplicateOutputFormat", resourceCulture);
		public static string FlightDiskSpaceWarningFormat => ResourceManager.GetString("FlightDiskSpaceWarningFormat", resourceCulture);
		public static string MenuComponentGalleryHeader => ResourceManager.GetString("MenuComponentGalleryHeader", resourceCulture);
		public static string ComponentGalleryWindowTitle => ResourceManager.GetString("ComponentGalleryWindowTitle", resourceCulture);
	}
}
